name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install echarts 1
      run: npm install echarts -S

    - name: Install echarts 2
      run: npm install ngx-echarts -S

    - name: Install echarts 3
      run: npm install @types/echarts -D
    #- name: Run tests
    #  run: npm run test:headless

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/multi-purpose-cms-angular s3://admin-dashboard-angular
